### ISSUE TITLE
Create PR for eqMac?

### ISSUE THREAD

**Issue by hpl002** [indiependente/autoEqMac#3]
Yo fellas!

Awesome project you have created. This exact idea just fell into my head yesterday and i am happy to see that someone has already taken on the challenge.

How would you feel about trying to integrate this directly into [eqMac](https://github.com/bitgapp/eqMac/issues/432)?   
Im sure this is a feature that users would be interested in.

I have a ongoing feature request [here](https://github.com/bitgapp/eqMac/issues/432).

I would be happy to put in some work one this if you could help me get started. From what i can see it should be fairly simple to offer AutoEq profiles as presets in eqMac. We can simply add them to the list that is already offered in the advanced settings:

![Screenshot 2020-12-30 at 01 13 44](https://user-images.githubusercontent.com/25330262/103321944-5638fa80-4a3c-11eb-8dc2-6a2fd5b3e1a6.png)

Could create a script that runs at a fixed interval and creates a profile for every new config available in AutoEq. This can then automatically be offered as a PR by a github bot to eqMac. 

From what i understand there is some conversion that needs to be done, but from what i can remember this is documented in the usage section of autoEq, and i suspect that you have done the same conversion here in your own project?

Thoughts?

BR

Herman

**Comment by indiependente** [comment]
Hello @hpl002 ,

I'll try answer your questions.

> How would you feel about trying to integrate this directly into eqMac?

It depends on what you mean with _integrate_: 
as you are surely aware, eqMac is a Swift application so porting this feature into the app means rewriting at least the core functionality of this tool into eqMac itself and maybe writing some UI for it as well. 
I personally wouldn't have much time to do this type of work unfortunately, but I think the eqMac devs might actually want to do integrate this feature, but I'm not sure how high in their priorities is it. 
Here is a link to a message by @nodeful sent on the official Discord channel back when I posted the release of autoEqMac: 
https://discord.com/channels/696460465601249320/696460466414813197/772824193145503784

> We can simply add them to the list that is already offered in the advanced settings

In this case it would be trivial to add a subcommand to generate all the profile files for each pair of headphones retrieved from AutoEq, but honestly I don't think this is the kind of UX eqMac's devs might want to offer to their users: scrolling through this huge list of headphones (where each might have several variants) doesn't sound very appealing to me.
So here I think it's up to them to decide how they want to allow users to search and select the database of eq profiles.

> Could create a script that runs at a fixed interval and creates a profile for every new config available in AutoEq. This can then automatically be offered as a PR by a github bot to eqMac.

Yes, definitely this might be a good solution to add new profiles from AutoEq in the eqMac repo, if that is what the devs want.

>  i suspect that you have done the same conversion here in your own project?

Yes, it's basically what `autoEqMac` does under the hood.


I hope what I said here makes sense to you.

Cheers,
Francesco

**Comment by hpl002** [comment]
Hi!

This makes a lot of sense. I too have no inner urge to dive into swift development, but if the issue gains any traction over on their repo then i will give it a try.

I absolutely agree about the rendering of audio listening devices(headphones), having a list of 2000+ entries is not appealing. The UX would have to be done in a thoughtful way.

Closing the issue for now, as this is a feature that pertains to eqMac. 

Appreciate the quick reply!

BR

Herman
