### ISSUE TITLE
Providing my own headphone measurement file.

### ISSUE THREAD

**Issue by yaelmndrp** [indiependente/autoEqMac#35]
Hi, I was wondering if there's any way for me to specify my own .csv file containing my headphone's measurements, since my headphones are not in the AutoEQ project (KZ EDX).

**Comment by indiependente** [comment]
Hi @yaelmndrp,

So if I get this right, you'd like for a way to translate your CSV file into the EqMac format.  Am I correct?
If that's the case, please share the CSV header.

Thanks.

**Comment by yaelmndrp** [comment]
Of course! Here's the .CSV file containing my headphone's (KZ EDX) frequency response measurement.

[KZ EDX Frequency Response](https://github.com/yaelmndrp/my-headphones-measurements/blob/main/KZEDXFR.csv)

**Comment by indiependente** [comment]
Thanks. I'll take a look in the next few days and provide a flag to import your own custom frequency response file.

**Comment by yaelmndrp** [comment]
Yeah, a flag to provide our own frequency response file would be very helpful, thanks!

**Comment by indiependente** [comment]
Hi @yaelmndrp,

I looked at this, and for how much I'd love to integrate this cool feature into autoEqMac I think going from a raw frequency response file to an EqMac-compatible output JSON file goes a tiny bit beyond the scope of this project.
See, there are a few steps in between the conversion which I'm going to explain below:
```
raw frequency response csv -> parametric EQ -> autoEqMac -> EqMac
```

The first step is a conversion which requires some data processing and there are already tools out there to perform such processing, like [AutoEq](https://github.com/jaakkopasanen/AutoEq) itself which is battle-tested and has started the whole project.
[Here](https://github.com/jaakkopasanen/AutoEq/tree/master/autoeq#usage) you can see how the autoEq python module can be used to go exactly from a raw frequency profile CSV file.

So, what I'd suggest is to convert the raw FR profile to a Fixed Band EQ file similar to [this one](https://github.com/jaakkopasanen/AutoEq/blob/master/results/Rtings/over-ear/Audio-Technica%20ATH-M50x/Audio-Technica%20ATH-M50x%20FixedBandEQ.txt) and in the meanwhile I'll work on a feature to import custom FixedBandEQ files.

This is the example usage you can read about in the main README file:
```
python -m autoeq --input-file="measurements/oratory1990/data/over-ear/Sennheiser HD 800.csv" --output-dir="my_results" --target="targets/harman_over-ear_2018_wo_bass.csv" --max-gain=24 --parametric-eq --parametric-eq-config=4_PEAKING_WITH_LOW_SHELF,4_PEAKING_WITH_HIGH_SHELF --bass-boost=6 --convolution-eq --fs=48000 --bit-depth=32 --f-res=16
```

I hope that sounds reasonable to you 😃 

P.S.
You could even open a PR to add your custom FR file for your headphones to autoEq repository, in case they are missing such a model!

P.P.S.
Your KZ EDX are not any of those listed by autoEqMac?
<img width="452" alt="Screenshot 2024-11-03 at 19 55 38" src="https://github.com/user-attachments/assets/2f97661c-e927-441b-8673-d7baa32537d0">

**Comment by yaelmndrp** [comment]
I think I will open a PR to include my FR file on AutoEQ, and no, none of those models are my headphones' model. Anyways, thanks for the guidance!

**Comment by indiependente** [comment]
Thanks for understanding.
No problem, I will close this issue and work on the fixed band EQ input feature.
