### ISSUE TITLE
could not find EQ data for headphones ... : eq metadata name not found

### ISSUE THREAD

**Issue by tiburcio-b** [indiependente/autoEqMac#4]
Can't get the file for any device.

🎧 autoEqMac - EqMac preset generator powered by AutoEq
Please select headphones model:
🎧 >>> [model]
👉 You selected: [model]
2021/02/09 18:30:08 ⛔️ could not find EQ data for headphones [model] : eq metadata name not found

[Process completed]

**Comment by MaluNoPeleke** [comment]
Same problem for me:

could not find EQ data for headphones step Beyerdynamic Custom One Pro (step 3): eq metadata name not found
exit status 1

**Comment by indiependente** [comment]
Hello,

Sorry for the late reply.

I just tried retrieving the EQ for the _Beyerdynamic Custom One Pro (step 3)_ headphones mentioned by @MaluNoPeleke and it succeded.

Here is a GIF of the process working on a fresh install of the tool.

![out](https://user-images.githubusercontent.com/3093285/111032050-6f7a0200-8402-11eb-99f1-0f8655e905c0.gif)

**Comment by MaluNoPeleke** [comment]
Hmm, maybe I have another problem installing it:

`autoeqmac013 % go get github.com/indiependente/autoEqMac

 autoeqmac013 % autoEqMac                                

zsh: command not found: autoEqMac

 autoeqmac013 % go run autoEqMac                    
     
cannot find package "autoEqMac" in any of:

	/usr/local/Cellar/go/1.16.1/libexec/src/autoEqMac (from $GOROOT)

	/Users/peleke/go/src/autoEqMac (from $GOPATH)`

**Comment by indiependente** [comment]
Can you please try with 
```
go install github.com/indiependente/autoEqMac
```
?

**Comment by MaluNoPeleke** [comment]
A `go run github.com/indiependente/autoEqMac` solved the `zsh: command not found: autoEqMac` problem that I had with go get or go install and with version 0.1.3 I was able to generate the json as in your gif. Thanks for your work and support.

**Comment by indiependente** [comment]
Thank you for using this tool and feel free to suggest new features 😃
